### ISSUE TITLE
Unable to require this library with Clojure 1.10.0

### ISSUE THREAD

**Issue by danjrauch** [tonsky/net.async#3]
Hey, 

When I try to require this library I get an error that the call to core.ns failed due to a spec error. 

project.clj:

```
(defproject tyro "0.1.0-SNAPSHOT"
  :description "P2P File Sharing System"
  :url "https://github.com/danjrauch/tyro"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [org.clojure/core.async "0.7.559"]
                 [net.async/async "0.1.0"]
                 [org.clojure/tools.logging "0.5.0"]
                 [org.clojure/tools.cli "0.4.2"]]
  :main ^:skip-aot tyro.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

This is what I'm trying to run...
```
(ns tyro.core
  (:gen-class)
  (:require [clojure.core.async :refer [<!! <! >! >!! go]]
            [clojure.string :as str]
            [clojure.tools.logging :as logging]
            [clojure.tools.cli :refer [parse-opts]]
            [net.async/async :as net]
            [tyro.index :as ind]))

(defn -main
  [& args]
  (println "hey"))
```

And this is the amazing clojuresque error wall I get.  

```
Exception in thread "main" Syntax error macroexpanding clojure.core/ns at (tyro/core.clj:1:1).
Call to clojure.core/ns did not conform to spec.
        at clojure.lang.Compiler.checkSpecs(Compiler.java:6971)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:6987)
        at clojure.lang.Compiler.macroexpand(Compiler.java:7074)
        at clojure.lang.Compiler.eval(Compiler.java:7160)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:463)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval140$fn__144.invoke(form-init346708529611078759.clj:1)
        at user$eval140.invokeStatic(form-init346708529611078759.clj:1)
        at user$eval140.invoke(form-init346708529611078759.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec. {:clojure.spec.alpha/problems ({:path [:ns-clauses :refer-clojure :clause], :pred #{:refer-clojure}, :val :require, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-refer-clojure :clojure.core.specs.alpha/ns-refer-clojure], :in [2 0]} {:path [:ns-clauses :require :body :libspec :lib], :pred clojure.core/simple-symbol?, :val [net.async/async :as net], :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/libspec], :in [2 5]} {:path [:ns-clauses :require :body :libspec :lib+opts :lib], :pred clojure.core/simple-symbol?, :val net.async/async, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/libspec], :in [2 5 0]} {:path [:ns-clauses :require :body :prefix-list :prefix], :pred clojure.core/simple-symbol?, :val net.async/async, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/prefix-list :clojure.core.specs.alpha/prefix-list], :in [2 5 0]} {:path [:ns-clauses :require :body :flag], :pred #{:verbose :reload :reload-all}, :val [net.async/async :as net], :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-require :clojure.core.specs.alpha/ns-require], :in [2 5]} {:path [:ns-clauses :import :clause], :pred #{:import}, :val :require, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-import :clojure.core.specs.alpha/ns-import], :in [2 0]} {:path [:ns-clauses :use :clause], :pred #{:use}, :val :require, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-use :clojure.core.specs.alpha/ns-use], :in [2 0]} {:path [:ns-clauses :refer :clause], :pred #{:refer}, :val :require, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-refer :clojure.core.specs.alpha/ns-refer], :in [2 0]} {:path [:ns-clauses :load :clause], :pred #{:load}, :val :require, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-load :clojure.core.specs.alpha/ns-load], :in [2 0]} {:path [:ns-clauses :gen-class :clause], :pred #{:gen-class}, :val :require, :via [:clojure.core.specs.alpha/ns-form :clojure.core.specs.alpha/ns-gen-class :clojure.core.specs.alpha/ns-gen-class], :in [2 0]}), :clojure.spec.alpha/spec #object[clojure.spec.alpha$regex_spec_impl$reify__2509 0x64c63c79 "clojure.spec.alpha$regex_spec_impl$reify__2509@64c63c79"], :clojure.spec.alpha/value (tyro.core (:gen-class) (:require [clojure.core.async :refer [<!! <! >! >!! go]] [clojure.string :as str] [clojure.tools.logging :as logging] [clojure.tools.cli :refer [parse-opts]] [net.async/async :as net] [tyro.index :as ind])), :clojure.spec.alpha/args (tyro.core (:gen-class) (:require [clojure.core.async :refer [<!! <! >! >!! go]] [clojure.string :as str] [clojure.tools.logging :as logging] [clojure.tools.cli :refer [parse-opts]] [net.async/async :as net] [tyro.index :as ind]))}
        at clojure.spec.alpha$macroexpand_check.invokeStatic(alpha.clj:705)
        at clojure.spec.alpha$macroexpand_check.invoke(alpha.clj:697)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.lang.Compiler.checkSpecs(Compiler.java:6969)
        ... 44 more
```

**Comment by tonsky** [comment]
PRs are welcome!
